### ISSUE TITLE
Site crashes when price is to high

### ISSUE THREAD

**Issue by Tijndagamer** [fullstck/leiestedet#2]
When posting, after submitting the site will crash if the price is too high.

**Comment by FredrikAugust** [comment]
Define too high

**Comment by Tijndagamer** [comment]
It was 900000000000000000000000000000000000

**Comment by FredrikAugust** [comment]
Well, apparently, Postgresql limits the integer column to 2^32, so I'll just limit it client side

**Comment by FredrikAugust** [comment]
Scratch that, client- and server-side

**Comment by FredrikAugust** [comment]
Fixed in ae466ca2d7161196feaf9399e405576798e30fc6
